In [ ]:
import pickle, gzip
import numpy as np

In [ ]:
## load data
 
f = gzip.open('mnist_10000.pkl.gz', 'rb')
trainData, trainLabels, valData, valLabels, testData, testLabels = pickle.load(
    f, encoding='latin1')
f.close()
 
print("training data points: {}".format(len(trainLabels)))
print("validation data points: {}".format(len(valLabels)))
print("testing data points: {}".format(len(testLabels)))

training data points: 10000
validation data points: 2000
testing data points: 2000


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
## train model
 
for k in [1, 3, 5, 9, 15, 25, ]:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(trainData, trainLabels)
    # KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
    #            metric_params=None, n_jobs=1, n_neighbors=5, p=2,
    #            weights='uniform')
 
    score = model.score(valData, valLabels)
    print(k, score) 

1 0.947
3 0.953
5 0.948
9 0.9405
15 0.9335
25 0.9235


In [ ]:
# re-train our classifier using the best k value and predict the labels of the
# test data
model = KNeighborsClassifier(n_neighbors=3)
model.fit(trainData, trainLabels)
accuracy = model.score(testData, testLabels)
print("Achieved accuracy of %.2f%% on test data" % (accuracy*100))

Achieved accuracy of 92.35% on test data


In [ ]:
from sklearn.metrics import classification_report
# show a final classification report demonstrating the accuracy of the classifier
# for each of the digits
predictions = model.predict(testData)
print("Classification Report")
print(classification_report(testLabels, predictions))

Classification Report
              precision    recall  f1-score   support

           0       0.94      1.00      0.97       175
           1       0.90      1.00      0.95       234
           2       0.98      0.89      0.93       219
           3       0.91      0.91      0.91       207
           4       0.94      0.94      0.94       217
           5       0.91      0.91      0.91       179
           6       0.95      0.97      0.96       178
           7       0.89      0.91      0.90       205
           8       0.95      0.80      0.87       192
           9       0.89      0.90      0.89       194

   micro avg       0.92      0.92      0.92      2000
   macro avg       0.92      0.92      0.92      2000
weighted avg       0.92      0.92      0.92      2000



In [ ]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix")
print(confusion_matrix(testLabels, predictions))

Confusion Matrix
[[175   0   0   0   0   0   0   0   0   0]
 [  0 234   0   0   0   0   0   0   0   0]
 [  5   5 196   0   0   0   3   8   2   0]
 [  0   1   1 189   0   4   2   4   3   3]
 [  0   3   0   0 203   0   2   0   1   8]
 [  2   0   0   7   1 163   1   2   0   3]
 [  2   1   0   0   1   1 173   0   0   0]
 [  0  11   0   1   2   1   0 186   0   4]
 [  3   4   4   8   3   8   1   3 154   4]
 [  0   1   0   3   6   2   0   6   2 174]]
