# Python Implementation using NumPy
Let's start by loading the iris dataset, which contains information about from iris flowers.

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
# load iris dataset 
iris = datasets.load_iris()
X = iris.data[:, :] 
y = (iris.target != 0) * 1   # original dataset has 4 classes. We make y binary.

In [3]:
print(X[:10, :])
print(y[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 0 0 0 0 0 0 0 0 0]


We have 4 input features in the dataset. The target variable here is which type of iris flower it is (there are 4 types in the dataset). To make it binary, we will only classify whether the flower is Type 0 or not.

split the dataset into train and test

In [5]:
# random shuffle
a = np.arange(150)
np.random.seed(42)
np.random.shuffle(a)
test = list(a[0:30])
train = list(a[30:150])

In [7]:
# train/test split
X_train = X[train]
X_test = X[test]

In [8]:
y_train = y[train]
y_test = y[test]

write all the helper functions we need for logistic regression:

In [9]:
## general functions
def sigmoid(z):
  return 1 / (1 + np.exp(-z))
  
def zed(W, b, x):
  # Computes the weighted sum of inputs
  return x.dot(W) + b
 
def prob_prediction(W, b, x):
  # Returns the probability after passing through sigmoid
  return sigmoid(zed(W, b, x))
 
def cost_func(h, y):
  return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()
 
## evaluation functions 
# label predictions
def predict(W, b, x):
  prob = prob_prediction(W, b, x)
  return prob >= 0.5
 
# accuracy evaluation
def evaluate(h_test, y):
  return (h_test == y).mean() * 100

we can perform the training and testing:

In [10]:
## initialization
W = np.random.uniform(low=-0.1, high=0.1, size=X_train.shape[1])
b = 0.0
learning_rate = 0.1
epochs = 20000

In [13]:
## training: fit the model to training set
print('Training:')
for i in range(epochs):
  # calculate predictions
  y_predict = prob_prediction(W, b, X_train) 
  
  # calculate error and cost (mean squared error)
  cost = cost_func(y_predict, y_train)
 
  # calculate gradients
  W_gradient = (1.0/len(X_train)) * (y_predict - y_train).dot(X_train)
  b_gradient = (1.0/len(X_train)) * np.sum(y_predict - y_train)
    
  # diagnostic output
  if i % 1000 == 0: print("Epoch %d: Cost = %f" % (i, cost))
      
  # update parameters
  W = W - (learning_rate * W_gradient)
  b = b - (learning_rate * b_gradient)

Training:
Epoch 0: Cost = 0.725486
Epoch 1000: Cost = 0.007366
Epoch 2000: Cost = 0.003973
Epoch 3000: Cost = 0.002771
Epoch 4000: Cost = 0.002147
Epoch 5000: Cost = 0.001761
Epoch 6000: Cost = 0.001498
Epoch 7000: Cost = 0.001306
Epoch 8000: Cost = 0.001160
Epoch 9000: Cost = 0.001045
Epoch 10000: Cost = 0.000952
Epoch 11000: Cost = 0.000875
Epoch 12000: Cost = 0.000809
Epoch 13000: Cost = 0.000754
Epoch 14000: Cost = 0.000706
Epoch 15000: Cost = 0.000664
Epoch 16000: Cost = 0.000627
Epoch 17000: Cost = 0.000594
Epoch 18000: Cost = 0.000564
Epoch 19000: Cost = 0.000538


In [14]:
## evaluation
print('Testing:')
test_set_predictions = predict(W, b, X_test)
print('Accuracy percentage:', evaluate(test_set_predictions, y_test))

Testing:
Accuracy percentage: 100.0
